# config.py
 
WINDOW_DAYS = 30
INTERVALS_PER_DAY = 96
SIGNATURE_LENGTH = WINDOW_DAYS * INTERVALS_PER_DAY  # 2880
 
RADIUS_METERS = 175
CORRELATION_THRESHOLD = 0.95
MIN_OVERLAP_POINTS = 2000
TOP_K_NEIGHBORS = 5
 
RAW_DATA_DIR = "data/raw"
DAILY_RAW_DIR = "data/raw/daily"
PROCESSED_DATA_DIR = "data/processed"
SIGNATURE_DIR = "data/processed/signatures"
OUTPUT_DIR = "data/outputs"
STATE_DIR = "data/state"

EARTH_RADIUS_M = 6371000
ARRAYSIZE = 10000
MAX_RETRIES = 3